# Generated by Django 4.2.30 on 2026-05-23 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2)),
                ('level', models.CharField(default='brevet', max_length=32)),
                ('source_file', models.CharField(help_text="Path relative to ASSETS_DIR, e.g. 'french/bio.pdf'.", max_length=512)),
                ('pdf_path', models.CharField(blank=True, help_text='Absolute path to the processed, structured PDF (citation source).', max_length=512)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Mean OCR confidence (0–100); a corpus quality signal.', max_digits=5, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ('language', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology & Earth Sciences'), ('informatics', 'Informatics'), ('grammar', 'Grammar'), ('reading', 'Reading & Activities'), ('french', 'French Language'), ('english', 'English Language')], max_length=32, unique=True)),
                ('name_en', models.CharField(max_length=128)),
                ('name_fr', models.CharField(max_length=128)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Accent-folded, lowercase keywords used to route queries to this subject.')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'db_table': 'subjects',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=512)),
                ('path', models.CharField(blank=True, help_text="Breadcrumb, e.g. 'Optics > The Eye > Reduced eye'.", max_length=1024)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('ordinal', models.PositiveIntegerField(default=0, help_text='Order within the book.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.book')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.section')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ('book', 'ordinal'),
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2)),
                ('chunk_index', models.PositiveIntegerField(help_text='Order within the book.')),
                ('page_start', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('page_end', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('heading_path', models.CharField(blank=True, max_length=1024)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 of content for idempotent re-ingest / dedup.', max_length=64)),
                ('vector_id', models.UUIDField(blank=True, help_text='Identifier of the embedding in the vector store.', null=True, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='catalog.book')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='catalog.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='catalog.subject')),
            ],
            options={
                'db_table': 'chunks',
                'ordering': ('book', 'chunk_index'),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.subject'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['book', 'ordinal'], name='ix_section_order'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['language', 'subject'], name='ix_chunk_routing'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['book'], name='ix_chunk_book'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('book', 'chunk_index'), name='uq_chunk_book_index'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language', 'subject'], name='ix_book_routing'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('language', 'source_file'), name='uq_book_language_source'),
        ),
    ]
