# Generated by Django 4.2.30 on 2026-05-25 09:22
import hashlib

from django.db import migrations, models
import django.db.models.deletion


def _backfill_content_hash(apps, schema_editor):
    """Give existing books a document-level content_hash so a future re-upload of
    the same book is detected as a content duplicate. Must match ingest.document_hash:
    sha256 of the chunk texts joined by '\\n' in chunk_index order."""
    Book = apps.get_model("catalog", "Book")
    Chunk = apps.get_model("catalog", "Chunk")
    for book in Book.objects.all().iterator():
        texts = list(
            Chunk.objects.filter(book=book).order_by("chunk_index").values_list("content", flat=True)
        )
        digest = hashlib.sha256("\n".join(texts).encode("utf-8")).hexdigest()
        Book.objects.filter(pk=book.pk).update(content_hash=digest)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_chunk_content_fulltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of the normalised document text; for upload dedup detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='The (now frozen) book this one superseded via freeze-and-replace.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen')], db_index=True, default='active', help_text='Frozen books are kept (reversible) but excluded from retrieval.', max_length=8),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status', 'language', 'subject'], name='ix_book_status_routing'),
        ),
        migrations.RunPython(_backfill_content_hash, migrations.RunPython.noop),
    ]
