# Generated by Django 4.2.30 on 2026-05-25 10:17

from django.db import migrations, models
import django.db.models.deletion

from apps.catalog.data import taxonomy


def _seed_and_backfill(apps, schema_editor):
    """Seed default languages/school/grades and classify existing books under the
    default school + Grade 9 (the current Brevet corpus)."""
    Language = apps.get_model("catalog", "Language")
    School = apps.get_model("catalog", "School")
    Grade = apps.get_model("catalog", "Grade")
    Book = apps.get_model("catalog", "Book")
    for code, name, native, tess, subdir, folder in taxonomy.LANGUAGES:
        Language.objects.update_or_create(
            code=code,
            defaults={"name": name, "native_name": native, "tesseract": tess,
                      "ocr_subdir": subdir, "assets_folder": folder, "enabled": True},
        )
    school, _ = School.objects.update_or_create(
        code=taxonomy.DEFAULT_SCHOOL[1], defaults={"name": taxonomy.DEFAULT_SCHOOL[0], "enabled": True}
    )
    default_grade = None
    for name, code, ordinal in taxonomy.GRADES:
        g, _ = Grade.objects.update_or_create(
            code=code, defaults={"name": name, "ordinal": ordinal, "enabled": True}
        )
        if code == taxonomy.DEFAULT_GRADE_CODE:
            default_grade = g
    Book.objects.filter(school__isnull=True).update(school=school)
    Book.objects.filter(grade__isnull=True).update(grade=default_grade)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_content_hash_book_replaces_book_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('ordinal', models.PositiveSmallIntegerField(default=0, help_text='Sort order, e.g. 9 for Grade 9.')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ('ordinal', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Short code, e.g. 'en', 'fr', 'ar'.", max_length=8, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('native_name', models.CharField(blank=True, max_length=64)),
                ('tesseract', models.CharField(blank=True, help_text="Tesseract OCR language, e.g. 'eng'.", max_length=16)),
                ('ocr_subdir', models.CharField(blank=True, help_text='gpu_ocr_books results subfolder.', max_length=32)),
                ('assets_folder', models.CharField(blank=True, help_text="Corpus/uploads subfolder, e.g. 'english'.", max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'schools',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(help_text="Language code from the Language registry (e.g. 'en').", max_length=8),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='language',
            field=models.CharField(max_length=8),
        ),
        migrations.AddField(
            model_name='book',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.grade'),
        ),
        migrations.AddField(
            model_name='book',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.school'),
        ),
        migrations.RunPython(_seed_and_backfill, migrations.RunPython.noop),
    ]
